Tweak test to trigger error caused by cf4dd421
Error is

TypeError: metadata_fetcher() missing 2 required positional arguments: 'align_clusters' and 'item'

Order has to be changed since caching metadata does not seem to allow to hit the following lines:

if not filemeta.populated(clusters=self.align_clusters):
    filemeta.metadata = self.metadata_fetcher(filemeta).pop().metadata